title: The ultimate place for your childs
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6170213
  brandStrength: 0.7659575
  lightness: 0
  brandColors:
    - '#1c97d4'
    - '#ffffff'
    - '#88c3e7'
    - '#6ab1df'
    - '#cce0f3'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: kidsquare
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.49903
layout_spectrum: 0.5404255
