name: kidsquare
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24871
title: The ultimate place for your childs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c97d4'
    - '#ffffff'
    - '#88c3e7'
    - '#6ab1df'
    - '#cce0f3'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.14442620356567204
purpose: []
