name: kidsquare
favicon: null
layout_spectrum: 0.9972547271754593
typography_spectrum: 0.20917
title: The ultimate place for your childs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00adef'
    - '#fef200'
    - '#117fca'
    - '#5dbfe9'
  brandStrength: 0.503348674857989
  lightness: 0.5854842136614025
  saturation: 0.6115714046172798
  rhythmicContrast: 0.14442620356567204
purpose: []
